version: 2
updates:
- package-ecosystem: npm
  directory: "js"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 3
  labels:
    - "automerge"
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Los_Angeles
  labels:
    - "automerge"
  open-pull-requests-limit: 3
