[workspace]
members = [
  "client",
  "programs/hyperplane",
  "programs/hyperplane/fuzz",
  "programs/hyperplane/sim",
  "programs/hyperplane/viz",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"
