[package]
name = "spl-token-2022"
version = "0.5.0"
description = "Solana Program Library Token 2022"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-sbf = []
serde-traits = ["serde", "serde_with"]
# Remove these features once the underlying syscalls are released on all networks
default = ["zk-ops"]
zk-ops = []

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.7.2", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
solana-program = "1.14.10"
solana-zk-token-sdk = "1.14.10"
spl-memo = { version = "3.0.1", path = "../../memo/program", features = [ "no-entrypoint" ] }
spl-token = { version = "3.5",  path = "../program", features = ["no-entrypoint"] }
thiserror = "1.0"
serde = { version = "1.0.136", optional = true }
serde_with = { version = "1.14.0", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"
proptest = "1.0"
serial_test = "0.5.1"
solana-program-test = "1.14.10"
solana-sdk = "1.14.10"
serde_json = "1.0.81"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
