[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-client"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.3.0"

[dependencies]
async-trait = "0.1"
solana-cli-output = { version = "=1.14.10", optional = true }
solana-client = "=1.14.10"
solana-program-test = "=1.14.10"
solana-sdk = "=1.14.10"
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
spl-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
spl-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
spl-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
spl-token-2022 = { version = "0.5", path="../program-2022" }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:solana-cli-output"]
